/*
 * generated by Xtext
 */
package com.github.jmodel.mapper.plugin;

import org.eclipse.xtext.xbase.compiler.XbaseCompiler;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;

import com.github.jmodel.mapper.plugin.jvmmodel.MappingXbaseCompiler;
import com.github.jmodel.mapper.plugin.typesystem.MappingXbaseTypeComputer;



/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class MappingLanguageRuntimeModule extends com.github.jmodel.mapper.plugin.AbstractMappingLanguageRuntimeModule {

	public Class<? extends ITypeComputer> bindITypeComputer() {
		return MappingXbaseTypeComputer.class;
	}

	public Class<? extends XbaseCompiler> bindXbaseCompiler() {
		return MappingXbaseCompiler.class;
	}
	
}
