/*
* generated by Xtext
*/
package com.github.jmodel.mapper.plugin;

import com.github.jmodel.mapper.plugin.MappingLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MappingLanguageStandaloneSetup extends MappingLanguageStandaloneSetupGenerated{

	public static void doSetup() {
		new MappingLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

