/*
 * generated by Xtext
 */
package com.github.jmodel.mapper.plugin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MappingLanguageUiModule extends com.github.jmodel.mapper.plugin.ui.AbstractMappingLanguageUiModule {
	public MappingLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
